# Generated by Django 3.1 on 2020-08-18 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArClassifier', '0003_dataset_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='result',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='result',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='result_keyword', to='ArClassifier.result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='accuracy',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='f1_score',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='precision',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='recall',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=255)),
                ('k_value', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_classification', to='ArClassifier.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_classification', to='ArClassifier.project')),
                ('training_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_trainingset', to='ArClassifier.trainingset')),
            ],
        ),
    ]
