# Generated by Django 3.1 on 2020-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArClassifier', '0007_auto_20200822_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='type',
            field=models.CharField(default='Classification', max_length=255),
        ),
    ]
